[package]
name = "rust-city"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color_space = "0.5.3"
fltk = "1.2.29"
rand = "0.8.4"

[features]
